import { Worker } from "worker_threads";
import { config } from "../../config";
import { EvoMath } from "./math";
import { models } from "../models";

import {
  ResponseInputItem,
  Tool,
} from "openai/resources/responses/responses.js";
import HandleTools from "../tools";
import { MaturationPrompt, PlasticityPrompt } from "../prompts";
import { PLASTICITY_TOOLS } from "./tools";
import { CommunicationClient } from "../communication";
import { Socket } from "socket.io-client";
import { db } from "../db/db";
import { tokenUsage } from "../db/schema";

/*
    This is the evolution section of the Lark framework, while we have potential ideas generated by the master agent on discussions with the stakeholders, now we begin work on certain evolution of ideas and concepts.
*/
export class Evolution {
  private context: string;
  private strategies: string[];
  private stakeholders: Worker[];
  private stakeholderInfluenceWeight: number[];
  private aggregatedRankings: string[][];
  private strategyDictionary: object[];
  private generation = 0;
  private previousResponseID: string | undefined = undefined;
  private communicationClient: CommunicationClient;
  private io: Socket;

  constructor(context: string, strategies: string[], stakeholders: Worker[]) {
    this.context = context;
    this.strategies = strategies;
    this.stakeholders = stakeholders;
    this.stakeholderInfluenceWeight = [];
    this.aggregatedRankings = [];
    this.strategyDictionary = [];
    this.communicationClient = new CommunicationClient(
      "LARK_EVOLUTIONARY_PLATFORM",
    );
    this.communicationClient.connect();
    this.io = this.communicationClient.io;

    // Modify the strategies so each strategy has an associated number w/them
    for (let i = 0; i < this.strategies.length; i++) {
      this.strategyDictionary.push({
        id: i,
        strategy: this.strategies[i],
        bordaScore: 0,
        fitness: 0,
      });
    }
  }

  public updateContext(newContext: string): void {
    this.context = this.context + newContext;
  }

  // Start the evolution subprocess
  public async start() {
    // Check if we ready.
    if (config.evolutionarySettings.maxGenerations > this.generation) {
      this.communicationClient.sendMessage(`
        @Master Agent, you have exhausted the maximum number of generations. With this, you can't **run any more**. Here's the final generations' report.
        The original Strategies: ${this.strategies.toString()}, now our full dictionary (with modifications and plasticity tweaks are):
        ${this.strategyDictionary.toString()}. We are using your provided context.
        This is a pre-recorded message that is used in hopes to improve evolution and ideas (as with the stakeholders) such that the master agent reaches a point where it's satisfied with the responses.
      `);
      return; // End early
    }
    // First get all aggregated scores
    for (const stakeholder of this.stakeholders) {
      stakeholder.postMessage({
        data: {
          strategies: JSON.stringify(this.strategyDictionary),
        },
        type: "RANK_STRATEGIES",
      });

      stakeholder.once("message", async (data: any) => {
        if (data.type == "RANK_STRATEGIES_RESULT") {
          this.aggregatedRankings.push(data.data.rankings); // Should be a 2D array.
          this.stakeholderInfluenceWeight.push(data.data.influenceWeight); // theoretically should be mapped one-on-one ?
          let totalWeight = this.stakeholderInfluenceWeight.reduce(
            (a, b) => a + b,
            0,
          );
          // Adjust weights based on normalization
          for (let i = 0; i < this.stakeholderInfluenceWeight.length; i++) {
            this.stakeholderInfluenceWeight[i] =
              this.stakeholderInfluenceWeight[i] / totalWeight;
          }
          /*
              As a result of the above, we now can associate the strategy ranking w/the stakeholder's weights.
          */
          if (this.aggregatedRankings.length === this.stakeholders.length) {
            await this.calculateBordaScore(); // Performing score auto-update basically...
            this.calculateFitness();
          }
          console.log(this.aggregatedRankings, this.strategyDictionary);
          let tempStrategyArray = [];
          // Check if probability of an individual strategy duplicating is within our randomly generated probability
          for (let i = 0; i < this.strategyDictionary.length; i++) {
            if (Math.random() <= this.generateDuplicationProbability(i)) {
              let mutatedData = this.strategyDictionary[i];
              // Also maturation inside here w/LLM
              const modelResponse = await models[0].provider?.responses.create({
                model: models[0].modelID,
                instructions:
                  MaturationPrompt +
                  `<scenario-context>${this.context}</scenario-context>`,
                previous_response_id: this.previousResponseID,
                input: mutatedData.strategy,
                reasoning: {
                  effort: "medium",
                },
              });
              if (config.storeUsage) {
                await db.insert(tokenUsage).values({
                  cost: modelResponse?.usage?.cost,
                  inputTokens: modelResponse?.usage?.input_tokens,
                  totalTokens: modelResponse?.usage?.total_tokens,
                });
              }
              mutatedData.strategy = modelResponse?.output_text; // Reassign the data.
              // Create new entry at end?
              tempStrategyArray.push(mutatedData);
            }
          }
          this.strategyDictionary = [
            ...this.strategyDictionary,
            ...tempStrategyArray,
          ];
          // Also push same votes, original ID should correspond to aggregatedRankings index
          // this.aggregatedRankings.push()
          // Congrats! Duplication & Maturation are now finished.
          // For plasticity
          // Now we run this.inference
          await this.inference(PlasticityPrompt, PLASTICITY_TOOLS);
          // Maybe chat?
          // How do we return if the inference is finished?
          // I got it!
          this.communicationClient.sendMessage(`
            Report with evolution outcomes for generation ${this.generation}:
            The original Strategies: ${this.strategies.toString()}, now our full dictionary (with modifications and plasticity tweaks are):
            ${this.strategyDictionary.toString()}. We are using your provided context.
            This is a pre-recorded message that is used in hopes to improve evolution and ideas (as with the stakeholders) such that the master agent reaches a point where it's satisfied with the responses.
            @Master Agent, please decide whether to continue generating after deliberating with stakeholders, and then call the resume_evolution tool if so after calling the update_evolutionary_context tool if needed (appends to existing context of the situation).
          `);
        }
      });
    }
    this.generation++;
  }

  // Tools to generate the probability
  private generateDuplicationProbability(index: number) {
    if (index < 0 || index >= this.strategyDictionary.length) return 0;
    return (
      1 /
      (1 +
        Math.exp(
          -(
            this.strategyDictionary[index].fitness -
            this.calculatePopulationFitness()
          ) / config.constants.tau,
        ))
    ); // See paper.
  }

  private calculatePopulationFitness() {
    let fitnessSum = 0;
    for (let i = 0; i < this.strategyDictionary.length; i++) {
      fitnessSum += this.strategyDictionary[i].fitness;
    }
    return fitnessSum / this.strategyDictionary.length;
  }
  private async calculateBordaScore() {
    for (let i = 0; i < this.strategyDictionary.length; i++) {
      let score = 0;
      for (let j = 0; j < this.aggregatedRankings.length; j++) {
        // Triple for loop because its 2D
        for (let k = 0; k < this.aggregatedRankings[j].length; k++) {
          // if the ranking is equal to the dictionary id then we add borda score.
          if (
            parseInt(this.aggregatedRankings[j][k]) ==
            this.strategyDictionary[i].id
          ) {
            score +=
              (this.aggregatedRankings[j].length - k) *
              this.stakeholderInfluenceWeight[j];
          }
        }
      }
      this.strategyDictionary[i].bordaScore = score;
    }
  }

  private async calculateFitness() {
    for (let i = 0; i < this.strategyDictionary.length; i++) {
      let fitness = 0;
      fitness =
        this.strategyDictionary[i].bordaScore *
        (1 -
          config.constants.lambda *
            Math.max(
              (EvoMath.calculateTokens(this.strategyDictionary[i].strategy) -
                config.constants.maxTokens) /
                config.constants.maxTokens,
            ));
      this.strategyDictionary[i].fitness = fitness;
    }
  }

  private async inference(instructions: string, tools: Tool[]) {
    let messages: ResponseInputItem[] = [];
    while (true) {
      const modelResponse = await models[0].provider?.responses.create({
        model: models[0].modelID,
        instructions:
          instructions + `<scenario-context>${this.context}</scenario-context>`,
        tools: tools,
        previous_response_id: this.previousResponseID,
        input: messages,
      });
      this.previousResponseID = modelResponse?.id;
      messages.push(...modelResponse?.output);
      if (config.storeUsage) {
        await db.insert(tokenUsage).values({
          cost: modelResponse?.usage?.cost,
          inputTokens: modelResponse?.usage?.input_tokens,
          totalTokens: modelResponse?.usage?.total_tokens,
        });
      }
      // Do some more stuff with for loop
      for (let i = 0; i < modelResponse?.output.length; i++) {
        if (modelResponse?.output[i]?.type === "function_call") {
          const toolResponse = await HandleTools(modelResponse?.output[i]);

          if (toolResponse.return) {
            // Get the final Response and append
            messages.push({
              type: "function_call_output",
              // @ts-expect-error Expected.
              call_id: modelResponse?.output[i]?.call_id, // this is correct, ignore it
              output: toolResponse.output,
            });
            messages.push({
              type: "message",
              role: "system",
              content: "You have reached the end of the turn.",
            });
            return;
          } else if (toolResponse.programPauseIntent) {
            // Overwrite strategy
            if (toolResponse.programInstructions == "OVERWRITE_STRATEGY") {
              try {
                this.strategyDictionary[
                  JSON.parse(modelResponse?.output[i].arguments).id
                ].strategy = JSON.parse(
                  modelResponse?.output[i].arguments,
                ).content;
                messages.push({
                  type: "function_call_output",
                  // @ts-expect-error Expected.
                  call_id: modelResponse?.output[i]?.call_id, // this is correct, ignore it
                  output: "Overwrote strategy successfully.",
                });
              } catch {
                messages.push({
                  type: "function_call_output",
                  // @ts-expect-error Expected.
                  call_id: modelResponse?.output[i]?.call_id, // this is correct, ignore it
                  output: "Overwriting the strategy failed for some reason.",
                });
              }
            }
          }
        }
      }
    }
  }
}
