import { Worker } from "worker_threads";
import { config } from "../../config";
import { EvoMath } from "./math";
import { models } from "../models";
import { ResponseInput, ResponseInputItem, ResponseOutputItem, Responses, Tool } from "openai/resources/responses/responses.js";
import HandleTools from "../tools";

/*
    This is the evolution section of the Lark framework, while we have potential ideas generated by the master agent on discussions with the stakeholders, now we begin work on certain evolution of ideas and concepts.
*/
export class Evolution {
    private context: string;
    private strategies: string[];
    private stakeholders: Worker[];  
    private stakeholderInfluenceWeight: number[];
    private aggregatedRankings: string[][];
    private strategyDictionary: object[];
    private generation = 0;
    private previousResponseID: string | undefined = undefined;
    
    constructor(context: string, strategies: string[], stakeholders: Worker[]) {
        this.context = context;
        this.strategies = strategies;
        this.stakeholders = stakeholders;
        this.stakeholderInfluenceWeight = [];
        this.aggregatedRankings = [];
        this.strategyDictionary = [];
        // Modify the strategies so each strategy has an associated number w/them
        for (let i = 0; i < this.strategies.length; i++) {
            this.strategyDictionary.push({
                'id': i,
                'strategy': this.strategies[i],
                'bordaScore': 0,
                'fitness': 0
            });
        }
    }

    // Start the evolution subprocess
    public async start() {


        // First get all aggregated scores        
        for (const stakeholder of this.stakeholders) {
            await stakeholder.postMessage({
                'data': {
                    'strategies': JSON.stringify(this.strategyDictionary),
                },
                'type': 'RANK_STRATEGIES'
            });

            stakeholder.on('message',  async (data: any) => {
                if (data.type == 'RANK_STRATEGIES_RESULT') {
                    this.aggregatedRankings.push(data.data.rankings); // Should be a 2D array.
                    this.stakeholderInfluenceWeight.push(data.data.influenceWeight); // theoretically should be mapped one-on-one ?
                    // Adjust weights based on normalization
                    for (let i = 0; i < this.stakeholderInfluenceWeight.length; i++) {
                        this.stakeholderInfluenceWeight[i] = this.stakeholderInfluenceWeight[i] / this.stakeholderInfluenceWeight.reduce((a, b) => a + b, 0);
                    }
                    /*
                        As a result of the above, we now can associate the strategy ranking w/the stakeholder's weights.
                    */
                    if (this.aggregatedRankings.length === this.stakeholders.length) {
                        await this.calculateBordaScore(); // Performing score auto-update basically...
                        this.calculateFitness();                                                
                    }
                    let tempStrategyArray = [];
                    // Check if probability of an individual strategy duplicating is within our randomly generated probability
                    for (let i = 0; i < this.strategyDictionary.length; i++) {
                        if (Math.random() <= this.generateDuplicationProbability(i)) {
                            // Create new entry at end?
                            tempStrategyArray.push(this.strategyDictionary[i]);
                        }
                    }
                    this.strategyDictionary = [...this.strategyDictionary, ...tempStrategyArray];
                    // Congrats! Duplication is now finished.                    
                    
                }
            });
        }
    }

    // Tools to generate the probability
    private generateDuplicationProbability(index: number) {
        if (index < 0 || index >= this.strategyDictionary.length) return 0;
        return 1/(1+Math.exp(-(this.strategyDictionary[index].fitness - this.calculatePopulationFitness())/config.constants.tau)) // See paper.
    }

    private calculatePopulationFitness() {
        let fitnessSum = 0;
        for (let i = 0; i < this.strategyDictionary.length; i++) {
            fitnessSum += this.strategyDictionary[i].fitness;
        }
        return fitnessSum/this.strategyDictionary.length;
    }
    private async calculateBordaScore() {
        for (let i = 0; i < this.strategyDictionary.length; i++) {
            let score = 0;
            for (let j = 0; j < this.aggregatedRankings.length; j++) {
                // Triple for loop because its 2D
                for (let k = 0; k < this.aggregatedRankings[j].length; k++) {
                    // if the ranking is equal to the dictionary id then we add borda score.
                    if (parseInt(this.aggregatedRankings[j][k]) == this.strategyDictionary[i].id) {
                        score += ((this.aggregatedRankings[j].length - k) * this.stakeholderInfluenceWeight[j]);
                    }
                }
            }
            this.strategyDictionary[i].bordaScore = score;
        }
    }

    private async calculateFitness() {
        for (let i = 0; i < this.strategyDictionary.length; i++) {
            let fitness = 0;
            fitness = this.strategyDictionary[i].bordaScore * (1-config.constants.lambda * (Math.max((EvoMath.calculateTokens(this.strategyDictionary[i].strategy)-config.constants.maxTokens)/config.constants.maxTokens)))
            this.strategyDictionary[i].fitness = fitness;
        }
    }

    private async inference(instructions: string, tools: Tool[]) {
        const messages: ResponseInputItem[] = []
        const modelResponse = await models[0].provider?.responses.create({
            'model': models[0].modelID,
            'instructions': instructions + `<scenario-context>${this.context}</scenario-context>`,
            'tools': tools,
            'previous_response_id': this.previousResponseID,
            'input': messages,
        });
        this.previousResponseID = modelResponse?.id;
        messages.push(...modelResponse?.output);
        for (let i = 0; i < modelResponse?.output.length; i++) {
            if (modelResponse?.output[i]?.type === 'function_call') {
                const toolResponse = await HandleTools(modelResponse?.output[i]);
                if ((await toolResponse).return) {
                    // Get the final Response and append
                    messages.push({
                        'type': 'function_call_output',
                        // @ts-expect-error Expected.
                        'call_id': modelResponse?.output[i]?.call_id, // this is correct, ignore it
                        'output': toolResponse.output,
                    });
                    messages.push({
                        'type': 'message',
                        'role': 'system',
                        'content': 'You have reached the end of the turn.'
                    })   
                }
            }
        }
    }
}